### ISSUE TITLE
can't find otool

### ISSUE THREAD

**Issue by Achilles1988** [darwin/otx#4]
(system-10.9,xcode- 5.1)Every time i use this tool, it caught an exception. 
I try 2 modify like this:
- (NSString_)pathForTool:(NSString_)toolName
  {
  return [NSString pathWithComponents:[NSArray arrayWithObjects: @"/", @"usr", @"bin", toolName, nil]];
  }
  and it work...

**Comment by darwin** [comment]
should be fixed by 776a2532e5048c3511ae9c438ea1c209a1aff7a9
